export const experiences = [
   {
      company: 'STC Services',
      role: 'Software Developer',
      location: 'Dubai, UAE',
      start: '09/2023',
      end: 'Present',
      summary:
         'Utilizing .NET 8 and microservices, I contribute to digital identity solutions, focusing on backend development and ensuring smooth deployment processes.',
      achievements: [
         'Developed .NET 8 APIs for core features and reusable packages, improving dev speed and standardization across projects.',
         'Applied microservices architecture principles to isolate functionality, reducing downtime risk and lowering hosting costs through lighter App Service deployments.',
         'Contributed to a comprehensive authentication and permission-based authorization system that supports varied user roles.',
         'Built real-time user location tracking with SignalR to map movement and trigger restricted-area alerts.',
         'Deployed production apps via Azure VMs with IIS and used Azure App Services for faster development-stage releases.',
         'Set up Azure DevOps pipelines to automate builds and deployments, cutting manual steps and release errors.',
         'Integrated Outlook APIs to sync event creation so users can schedule meetings without duplicate entry.',
         'Used Dlib facial recognition to verify identities and track users for facility access and presence logging.',
      ],
      tech: [
         '.NET 8',
         'C#',
         'Microservices',
         'Azure App Service',
         'Azure VMs',
         'Azure Pipelines',
         'IIS',
         'Azure DevOps',
         'SignalR',
         'Outlook APIs',
      ],
   },
   {
      company: 'Digital Revamp',
      role: 'Full Stack Developer',
      location: 'Fanar, Lebanon',
      start: '04/2023',
      end: '08/2024',
      summary:
         'Full stack developer, utilizing C# and the renowned ASP.Net Core, and Microsoft SQL Server.',
      achievements: [
         'Used Entity Framework (Code First) for backend data handling across multiple modules.',
         'Developed a timesheet system using ASP.NET MVC and jQuery for internal users (~50-100), enabling efficient entry and tracking of work hours.',
         'Implemented reporting features to visualize logged hours, flag underperformers, and segment time by project, client, and department.',
         'Incorporated HR features to ensure efficient record-keeping and management of employee data.',
      ],
      tech: [
         'ASP.NET Core',
         'C#',
         'Entity Framework',
         'SQL Server',
         'ASP.NET MVC',
         'jQuery',
         'Reporting',
      ],
   },
   {
      company: 'CME',
      role: 'Software Engineer Intern',
      location: 'Beirut, Lebanon',
      start: '06/2023',
      end: '07/2023',
      summary:
         'Software engineering intern building web features and automation for location-focused products.',
      achievements: [
         'Built a location tracker web app using ReactJS, NestJS, Firebase, and MongoDB with routing and waypoint features.',
         'Integrated YELP and HERE APIs for location and restaurant data, and led automated testing using Cypress (frontend) and Jest (backend).',
      ],
      tech: [
         'ReactJS',
         'NestJS',
         'Firebase',
         'MongoDB',
         'YELP API',
         'HERE API',
         'Cypress',
         'Jest',
      ],
   },
]
